# Generated by Django 5.1.7 on 2025-03-20 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('celular', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Número de celular inválido.')])),
                ('rm', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
